# -*- coding: utf-8 -*-
"""Chapter 8 綜合範例+習題

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134TcVSvGQHHi7hBsh8R_T_-A5WMlepPS
"""

#綜合範例11:
#試撰寫一程式，以一不定迴圈要求使用者輸入字串，檢視若字串是以B字元開頭，則將此字串加入lst串列中，最後將其印出。當使用者輸入的end時將結束輸入的動作。
#1. 輸入輸出:
#(1)範例輸入:
#Block
#Apple
#Banana
#Cathy
#Boy
#end
#(2)範例輸出
#['Block' , 'Banana' , 'Boy']

#2.參考程式:

lst= []
while True:
   str = input ()
   if str != 'end':
     if str.startswith ('B'):
       lst.append(str)
   else:
     break

print(lst)

#綜合範例12:
#試撰寫一程式，已依不定迴圈要求使用者輸入字串，將輸入的字串以空白為分隔字元，並處存於lst串列中，最後將其印出。

#1.輸入與書輸出樣本:
#I am a teacher.
#['I','am','a','teacher.']
#He is a student.
#['He','is','a','student.']
#Hello, world
#['Hello,','world']
#end

#2.參考程式:

lst = []
while True:
  str = input()
  if str != 'end':
      lst = str.split()
      print(lst)
  else:
    break

#綜合範例13:
#試撰寫一程式，隨機產生10個介於65~90的亂數，然後將其轉換為一對應於英文字母的字串。

#1.輸入輸出 1:
  #(1)範例輸入
      #無
  #(2)範例輸出
      #YCHUOPDQDJ
#2.輸入輸出 2:
  #(1)範例輸入
      #無
  #(2)範例輸出
      #QQGGNXCZCZ

#3.參考程式:

import random
str = ''
for i in range(1,11):
  randNum = random.randint(65,90)
  str += (chr(randNum))
print(str)

#綜合範例14:
#試撰寫一程式，輸入九個字串置放於一名為lst的字串，其長度不超過10個字元。接下來，每一列印出三個字串，並且向中靠齊。
# *提示:每一列印出三個字串，並且向中靠齊。

#1.輸入輸出:
  #(1)範例輸入
      #apple
      #orange
      #kiwi
      #banana
      #grape
      #pineapple
      #guava
      #cherry
      #blueberry
  #(2)範例輸出
    #|  apple  | |  orange  | |   kiwi    |
    #|  banana | |  grape   | | pineapple |
    #|  guava  | |  cherry  | | blueberry |

#2.參考程式:

lst =[]
for i in range(1,10):
    str = input()
    lst.append(str)

for k in range(1,10):
    if k % 3 != 0:
        print('|'+lst[k-1].center(15)+'|',end = '')
    else:
        print('|'+lst[k-1].center(15)+'|')

#綜合範例15：
#試撰寫一程式，輸入一名為str的字串與欲尋找的字串，將找到的字串以'Bright'字串取代之。
#若沒有玉找尋的字串，則印出'is not found'的訊息。
#1. 輸入輸出1:
#   (1)範例輸入
#      I make an appointment with Linda 
#      Linda
#   (2)範例輸出
#      I make an appointment with Bright
#2. 輸入輸出2:
#   (1)範例輸入
#      I make an appointment with Linda
#      Nancy
#   (2)範例輸出
#      Nancy is not found

#3. 參考程式:

str = input()
fstr = input()
if str.find(fstr) != -1:
    endStr = str.replace(fstr,'Bright')
    print(endStr)
else:
    print(fstr + 'is not found')

#Ch8 習題1
#試撰寫一程式，以不定數迴圈輸入以: 時:分:秒表示的時間數字，隨後將它拆解存放於串列。最後再將此串列輸出。當輸入為end則結束輸入資料。

# * 輸入與輸出樣本1:
#   20:12:56
#   hour: 22, min: 12, second:56
# * 輸入與輸出樣本2:
#   22:10:01
#   hour: 22, min: 10, second:01
#   end

#參考程式

lst = []
while True:
    str = input()
    if str != 'end':
        lst = str.split(':') 
        print('hour: %s, min: %s, second: %s' %(lst[0],lst[1], lst[2]))
    else:
        break

#Ch8 習題2 
#試撰寫一程式，輸入一變數名稱，然後判斷它是否為合法的變數名稱。假設取變數名稱的準則如下:
#A. 第一個字元需要英文字母
#B. 接下的字元可為英文字母或是數字
#C. 不可以為其他符號

# * 輸入與輸出樣本 1:
#   輸入:
#       Lo
#   輸出:
#       Valid variable name
# * 輸入與輸出樣本 2:
#   輸入:
#       7sdfja
#   輸出:
#       Invaid variable name
# * 輸入輸出樣本 3:
#   輸入:
#       abc123
#   輸出:
#       Valid variable name
# * 輸入輸出樣本 4:
#   輸入:
#       abc123%
#   輸出:
#       Invaid variable name

#參考程式

varName = input()
validVar = True

if not varName[0].isalpha():
    validVar = False
else:
    for i in range(0, len(varName)):
        if not varName[i].isalpha() and \
           not varName[i].isdigit():
              validVar = False
              break
if validVar:
    print('Valid variable name')
else:
    print('Invalid variable name')

#Ch8 習題3
#撰寫一程式，仿照綜合範例14，輸入九個字串置放於一名為lst的字串，其長度不常於10個字元。接下來，每一列映出三個字串，並向左靠齊。
#提示:每一個字串輸出欄位寬為15

#參考程式

lst=[]
for i in range(1,10):
    str = input()
    lst.append(str)

for k in range(1,10):
    if k % 3 != 0:
#center
         print("|"+lst[k-1].ljust(15)+"|",end=" ") 
    else:
         print("|"+lst[k-1].ljust(15)+"|")

#Ch8 習題4
#撰寫一程式，已依不一定迴圈要求使用者輸入字串，檢視若字串e字元尾端，則將此字串加入lst串列中，最後將其印出若字串e字元尾端，則將此字串加入lst串列中，最後將其印出。當使用者輸入end時將結束輸入的動作。

#參考程式

lst=[]
while True:
  str = input()
  if str !="end":
    if str.endswith("e"):
      lst.append(str)
  else:
    break

print(lst)

#Ch8 習題5
#撰寫一程式，輸入一含有20字元以上的字串，請將字串中的字元屬性印出，如他是英文字母、數字、空白，還是其他屬性。

#參考程式

str=input()
for i in range(len(str)):
  if str[i].isdigit():
    print(str[i]+":is a digit.")
  elif str[i].isalpha() and str[i].isupper():
    print(str[i]+":is upper alpha.")
  elif str[i].isalpha() and str[i].islower():
    print(str[i]+":is lower alpha.")
  elif str[i].isspace():
    print(str[i]+":is a space.")
  else:
    print(str[i]+":is a symbol character.")