# -*- coding: utf-8 -*-
"""week6資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQmljHbX2rKjAcqxuGFMPKikreRF4pWt
"""

#隨堂練習：身分證字號是否為奇數

id_last_digit = input("請輸入您身分證字號的尾數：")
id_last_digit = int(id_last_digit)
print(id_last_digit)
print(type(id_last_digit))
mudulo = id_last_digit % 2
ans = mudulo == 1    #奇數的餘數等於1 或是不等於0(==1改成!=0)
print(ans)

id_last_digit = input("請輸入您身分證字號的尾數：") #若為偶數則False
id_last_digit = int(id_last_digit)
print(id_last_digit)
print(type(id_last_digit))
mudulo = id_last_digit % 2
ans = mudulo == 1
print(ans)