# -*- coding: utf-8 -*-
"""week13資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qiei8CboYUH2ywEhGqTTwHFoiJ9YfNQL
"""

#計算字串字母中a,e,i,o,u母音個數

n_vowels = 0 
for i in 'azcbobobegghakl':
    if i in ['a', 'e', 'i', 'o', 'u']:       
       n_vowels += 1
print(n_vowels)

#計算出現幾個bob

test_str = 'azcbobobegghak'
n_char = len(test_str)
n_bobs = 0
for i in range(n_char - 2):
    if test_str[i:i+3] == 'bob':
        n_bobs += 1
print(n_bobs)

#計算 range(1, 101) 的樣本標準差

x = list(range(1, 101))
N = len(x)
x_bar = sum(x) / N
sse = 0
for xi in x:    
    squared_error = (xi - x_bar)**2
    sse += squared_error 
sample_mse = sse / (N-1)
sample_stdev = sample_mse**(0.5)
print(sample_stdev)

#寫作一個函數 get_fahrenheit() 將攝氏氣溫轉換為華氏氣溫

def get_fahrenheit(x):
    """
    Transform a Celsius degree into  Farenheit scale
    """
    fah = x * 9/5 + 32
    return fah
get_fahrenheit(32)