# -*- coding: utf-8 -*-
"""week9資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zpt9Xji97ysTU3Vqxh4iRxityAqZfTU
"""

#接上週week8隨堂練習：介於 x 到 y 之間的奇數加總為何（包含 x 與 y 假如它們是奇數）

"計數累計"

x = int(input("請輸入起始的整數:"))
y = int(input("請輸入終止的整數:"))
odd_summation = 0 # 歸零
i = x # start
while i <= y: # stop
    # task
    if i % 2 == 1:
        odd_summation = odd_summation + i # 數值累加
    i += 1 # step
print("======")
print(odd_summation)

"計數累計+數值累加"

x = int(input("請輸入起始的整數:"))
y = int(input("請輸入終止的整數:"))
odd_summation = 0 # 歸零
odd_counter = 0
i = x # start
while i <= y: # stop
    # task
    if i % 2 == 1:
        odd_counter += 1 # 計數累計
        odd_summation += i # 數值累加
        print("現在的整數是:{}, 奇數計數為{}個, 總和為{}".format(i, odd_counter, odd_summation))
    else:
        print("現在的整數是:{}, 奇數計數為{}個, 總和為{}".format(i, odd_counter, odd_summation))
    i += 1 # step
print("======")
print(odd_counter)
print(odd_summation)

#課堂內容：質數判斷

"不是質數"

x = int(input("請輸入一個正整數:"))
i = 1 # start
divisor_counter = 0 # 歸零
while i <= x: # stop
    if x % i == 0:
        divisor_counter += 1
        print("{}可以被{}整除".format(x, i))
        print("因數個數目前有{}個".format(divisor_counter))
        print("======")
    i += 1 # step
print("### Answer ###")
print("總共執行了{}次迴圈".format(i - 1))
print("{}共有{}個因數".format(x, divisor_counter))
if divisor_counter == 2:
    print("{}是質數".format(x))
else:
    print("{}不是質數".format(x))

"是質數"

x = int(input("請輸入一個正整數:"))
i = 1 # start
divisor_counter = 0 # 歸零
while i <= x: # stop
    if x % i == 0:
        divisor_counter += 1
        print("{}可以被{}整除".format(x, i))
        print("因數個數目前有{}個".format(divisor_counter))
        print("======")
    i += 1 # step
    if divisor_counter > 2:
        break
print("### Answer ###")
print("總共執行了{}次迴圈".format(i - 1))
if divisor_counter == 2:
    print("{}是質數".format(x))
else:
    print("{}不是質數".format(x))

#作業：Fizz-Buzz with while

i = 1
while i<=100:
  if i % 15 == 0:
      print("Fizz Buzz")
  elif i % 5 == 0:
      print("Buzz")
  elif i % 3 == 0:
      print("Fizz")
  else:
      print(i)
  i+=1