# -*- coding: utf-8 -*-
"""week12資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6yMcehQqi3aTNn9E9sipohp35A4cGkT
"""

"隨機數"

#產生一個

import random

random.randint(1, 1000)

#產生100個

random_integers = []
for i in range(100):
    rand_int = random.randint(1, 1000)
    random_integers.append(rand_int)
print(random_integers)
print(len(random_integers))

"find第一大第一小"

print(max(random_integers))
print(min(random_integers))

"find第二大第二小"

rand_int_unique = set(random_integers)
rand_int_unique_list = list(rand_int_unique)
print(rand_int_unique_list)
rand_int_unique_list.sort()
print(rand_int_unique_list[1])  # second min
print(rand_int_unique_list[-2]) # secomd max

"標記復仇者聯盟上映順序"

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for i, av in enumerate(avengers):
    print("第{}部上映的復仇者聯盟是:{}".format(i+1, av))

"zip應用"

years = [2012, 2015, 2018, 2019]
for year, movie in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))