# -*- coding: utf-8 -*-
"""week4資料科學.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11OzqmiHI5FYJxUNK3gdZKYs9EqR2M7b2
"""

作業:"""
(1)P2-27/28 溫度轉換

(2)P 2-29 計算俠客歐尼爾巔峰時期的 BMI 身體質量指
數

(3)P2-42 ：What did Ross say?

(4)P2-50 讓使用者輸入城市名稱與天氣，並印出「我在OOO，天氣OOO」

(5)P2-68 球員 BMI 與過重判斷 """

"第一題"

current_celsius = 28
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)

current_fahrenheit = 82.4
current_celsius = current_fahrenheit - 32 * 5 / 9
print(current_celsius)

current_fahrenheit = 82.4
current_celsius = (current_fahrenheit - 32) * 5 / 9
print(current_celsius)

"第二題"

shaq_height = 216
shaq_weight = 147

shaq_bmi = shaq_weight / (shaq_height/100)**2
print(shaq_bmi)

"第三題"

ross_said = 'Let\'s put aside the fact that you \"accidentally\" pick up my grandmother\'s ring.'
print(ross_said)

ross_said = "Let's put aside the fact that you \"accidentally\" pick up my grandmother's ring."
print(ross_said)

ross_said = """Let's put aside the fact that you "accidentally" pick up my grandmother's ring."""
print(ross_said)

"第四題"

city_name= input("請輸入城市")
current_weather = input("請輸入天氣")

print("我在{}，天氣{}".format(city_name, current_weather))

"第五題"

player_name = input("請輸入球員姓名")
player_height = input("請輸入球員身高")
player_weight = input("請輸入球員體重")
player_height = float(player_height)
player_weight = float(player_weight)
player_bmi = player_weight / (player_height/100)**2

print(player_name)
print(player_height)
print(player_weight)

player_bmi = player_weight / (player_height/100)**2
print(player_bmi)

print("{}的身體質量指數為:{:.2f}".format(player_name, player_bmi)) 
print("{}是否過重:{}".format(player_name, player_bmi > 30))

