# -*- coding: utf-8 -*-
"""week11資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zfbQHuJhcFu1F0lEc5KoZeW1wBzbJQX7
"""

the_avengers = {
    "Iron Man": "Tony Stark",
    "Captain America": "Steve Rogers",
    "Hulk": "Bruce Banner",
    "Thor": "Thor",
    "Black Widow": "Natasha Romanoff",
    "Hawkeye": "Clint Barton"
}

print(the_avengers.keys())
print(the_avengers.values())
print(the_avengers.items())

"紓困"

living_area=input("請輸入您的居住城市:")
print(living_area)


if living_area =="臺北市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 17005))
elif living_area == "新北市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 15500))
elif living_area == "桃園市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 15281))
elif living_area == "臺中市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 14596))  
elif living_area == "臺南市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 12388))
elif living_area =="高雄市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 13099))
elif living_area == "金門縣":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 11648))
elif living_area =="連江縣":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 11648))
elif living_area=="非六都縣市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 12388))
else:
  print("請重新輸入!")

living_area=input("請輸入您的居住城市:")
print(living_area)


if living_area =="臺北市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 17005))
elif living_area == "新北市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 15500))
elif living_area == "桃園市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 15281))
elif living_area == "臺中市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 14596))  
elif living_area == "臺南市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 12388))
elif living_area =="高雄市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 13099))
elif living_area == "金門縣":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 11648))
elif living_area =="連江縣":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 11648))
elif living_area=="非六都縣市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 12388))
else:
  print("請重新輸入!")

living_cost_dict = {
    '臺北市': 17005,
    '新北市': 15500,
    '桃園市': 15281,
    '臺中市': 14596,
    '臺南市': 12388,
    '高雄市': 13099,
    '金門縣': 11648,
    '連江縣': 11648,
    '非六都縣市': 12388
}
living_area = input('請輸入您的居住縣市:')
try:
    living_cost = living_cost_dict[living_area]
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
except KeyError:
    print("請重新輸入!!")