# -*- coding: utf-8 -*-
"""week8資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-uHgNdrratlIZL63hWLHt3NwVn_OTgN
"""

#隨堂練習：印出介於 x 到 y 之間的奇數（包含 x 與 y 假如它們是奇數）

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數:"))
i = x # 開始 start(用輸入的X當開始)
while i < y: # 結束 stop(用輸入的Y當結束)
    print(i) # 反覆執行的任務
    i += 2 # 間距 step

#隨堂練習：承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數:"))
i = x
counter = 0
while i <=10:
    if i % 2 == 1: # 判斷奇數
        counter += 1
    i += 1
print(counter)













