# -*- coding: utf-8 -*-
"""week8資料科學

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-uHgNdrratlIZL63hWLHt3NwVn_OTgN
"""

#作業：Fizz-Buzz
以 input() 函數請使用者輸入一個正整數
如果是 3 的倍數印出 "Fizz"
如果是 5 的倍數印出 "Buzz"
如果是 15 的倍數印出 "Fizz Buzz"
其他情況印出該正整數即可

user_int = int(input("請輸入一個正整數:"))
if user_int % 3 == 0:
  print("Fizz")
elif user_int % 5 == 0: #會先去抓第一塊if除以3print Fizz就不繼續了
    print("Buzz")

"FizzBuzz錯誤示範"
user_int = int(input("請輸入一個正整數:"))
if user_int % 3 == 0:
  print("Fizz")
  if user_int % 5 == 0: #此處if不是單獨的所以輸入5不會跑出Buzz
    print("Buzz")

user_int = int(input("請輸入一個正整數:"))
if user_int % 3 == 0:
  print("Fizz")
elif user_int % 5 == 0:
    print("Buzz")

"15錯誤示範，沒有出現Buzz"

user_int = int(input("請輸入一個正整數:"))
if user_int % 3 == 0:
  print("Fizz")
elif user_int % 5 == 0: #會先去抓第一塊if除以3print Fizz就不繼續了
    print("Buzz")

"15正確式子"

user_int = int(input("請輸入一個正整數:"))
if user_int % 3 == 0:
  print("Fizz")
if user_int % 5 == 0:
    print("Buzz")

"把除以15移到最前面，把else留給3,5,15之外的數字"

user_int = int(input("請輸入一個正整數:"))
if user_int % 15 == 0:
  print("Fizz Buzz")    #16在這一條是false
elif user_int % 5 == 0: #16在這一條也是false
    print("Buzz")
elif user_int % 3 == 0: #16在這條也還是false
  print("Fizz")
else:
  print(user_int)      #所以會輸出這條print自己本身的數字

#隨堂練習：印出介於 x 到 y 之間的奇數（包含 x 與 y 假如它們是奇數）

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數:"))
i = x # 開始 start(用輸入的X當開始)
while i < y: # 結束 stop(用輸入的Y當結束)
    print(i) # 反覆執行的任務
    i += 2 # 間距 step

#隨堂練習：承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數:"))
i = x
counter = 0
while i <=10:
    if i % 2 == 1: # 判斷奇數
        counter += 1
    i += 1
print(counter)